[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/var/run/supervisord.pid

[program:auth]
command=/run-service.sh dotnet /app/auth/AuthService.dll --urls http://127.0.0.1:5001
environment=MongoDB__DatabaseName=AuthDb,ASPNETCORE_ENVIRONMENT=Production
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:blog]
command=/run-service.sh dotnet /app/blog/BlogService.dll --urls http://127.0.0.1:5002
environment=MongoDB__DatabaseName=BlogDb,ASPNETCORE_ENVIRONMENT=Production
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:tour]
command=/run-service.sh dotnet /app/tour/TourService.dll --urls http://127.0.0.1:5003
environment=MongoDB__DatabaseName=TourDb,ASPNETCORE_ENVIRONMENT=Production
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:purchase]
command=/run-service.sh dotnet /app/purchase/PurchaseService.dll --urls http://127.0.0.1:5004
environment=MongoDB__DatabaseName=PurchaseDb,ASPNETCORE_ENVIRONMENT=Production,Services__Tour=http://127.0.0.1:5003
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:execution]
command=/run-service.sh dotnet /app/execution/TourExecutionService.dll --urls http://127.0.0.1:5005
environment=MongoDB__DatabaseName=TourExecutionDb,ASPNETCORE_ENVIRONMENT=Production,Services__Tour=http://127.0.0.1:5003,Services__Purchase=http://127.0.0.1:5004
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gateway]
command=dotnet /app/gateway/GatewayService.dll --urls http://127.0.0.1:5000
directory=/app/gateway
environment=ASPNETCORE_ENVIRONMENT=Docker
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
